### ISSUE TITLE
the virtual machine

### ISSUE THREAD

**Issue by jqzhao7** [system-pclub/rust-study#21]
The user name of the virtual machine is "user" and the password is "123".
Where do I download this?

**Comment by system-pclub** [comment]
https://psu.box.com/s/3psy6jjwc5l436jj8i4j0ljzc8r3h8xf

**Comment by jqzhao7** [comment]
> https://psu.box.com/s/3psy6jjwc5l436jj8i4j0ljzc8r3h8xf

thanks for your reply and thanks for your contribution for rust.

**Comment by thanhlecongg** [comment]
@system-pclub  Hi, the link seem to be dead. I wonder if you can update the link for virtual machine. Many thanks. Have a good day.
